import { test,expect,type APIRequestContext } from '@playwright/test';
import { Pool } from 'pg';
import { emptyDevice } from '../../lib/types';
const origin=process.env.TEST_BASE_URL||'http://localhost:3000';
const headers={Origin:origin};
const stamp=Date.now().toString().slice(-9);
if(!/^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(origin))throw new Error('验收测试只允许本地网址');
test.afterAll(async()=>{const pool=new Pool({connectionString:'postgresql://digitallab:local-development-only@127.0.0.1:54329/digitallab'});try{await pool.query('DELETE FROM devices WHERE code=ANY($1::text[])',[[`QA-${stamp}`,`IMPORT-${stamp}`,`UI-${stamp}`]]);await pool.query('DELETE FROM users WHERE email=ANY($1::text[])',[[`member-${stamp}@qa.local`,`extra-${stamp}`,`id-${stamp}`]]);}finally{await pool.end();}});
async function login(request:APIRequestContext,email='admin@digitallab.local',password='LocalLab-Review-2026!'){const r=await request.post('/api/auth',{headers,data:{email,password}});expect(r.status()).toBe(200);}
test('完整设备流程、权限隔离、附件与稳定二维码',async({request,playwright,page})=>{
  await login(request);
  const markdown='- **先检查耗材**\n- [官方说明](https://bambulab.com)\n\n<script>window.markdownInjected=true</script>\n<img src=x onerror="window.markdownInjected=true">\n[危险链接](javascript:alert(1))';
  const data={...emptyDevice,name:'验收设备',code:`QA-${stamp}`,model:'CF-24',category:'测试分类',room:'验收房间',owner:'验收负责人',ownerPhone:'010-12345678',manufacturerPhone:'010-87654321',precautions:markdown,price:'76543.21',internalNotes:'不应泄露的内部备注',supplier:'内部供应商',sop:[{title:'已核对的示例步骤',body:'验收测试内容，不用于真实设备操作'}],maintenance:[{id:'qa',date:'2026-10-06',kind:'校准',detail:'内部校准记录',nextDate:'2027-10-06'}]};
  const create=await request.post('/api/devices',{headers,data});expect(create.status()).toBe(201);const {id}=await create.json();expect(id).toMatch(/^[a-f0-9]{12}$/);
  const guest=await playwright.request.newContext({baseURL:origin});
  const member=await playwright.request.newContext({baseURL:origin});
  let publicFileId='',internalFileId='';let memberId='';
  try{
    expect((await guest.get(`/api/devices/${id}`)).status()).toBe(404);
    expect((await guest.post('/api/devices',{headers,data})).status()).toBe(401);
    const duplicate=await request.post('/api/devices',{headers,data});expect(duplicate.status()).toBe(409);
    expect((await request.post('/api/devices',{headers:{Origin:'https://evil.invalid'},data:{...data,code:'EVIL'}})).status()).toBe(403);
    const pdf=Buffer.from('%PDF-1.4\nfixture attachment\n%%EOF');
    const pub=await request.post('/api/files',{headers,multipart:{deviceId:id,kind:'manual',visibility:'public',file:{name:'说明书.pdf',mimeType:'application/pdf',buffer:pdf}}});expect(pub.status()).toBe(201);publicFileId=(await pub.json()).id;
    const internal=await request.post('/api/files',{headers,multipart:{deviceId:id,kind:'contract',visibility:'public',file:{name:'合同.pdf',mimeType:'application/pdf',buffer:pdf}}});expect(internal.status()).toBe(201);internalFileId=(await internal.json()).id;
    expect((await guest.get(`/api/files/${publicFileId}`)).status()).toBe(404);
    expect((await guest.get(`/api/files/${internalFileId}`)).status()).toBe(404);
    const invalidUpload=await request.post('/api/files',{headers,multipart:{deviceId:id,kind:'manual',visibility:'public',file:{name:'fake.pdf',mimeType:'application/pdf',buffer:Buffer.from('<script>unsafe</script>')}}});expect(invalidUpload.status()).toBe(400);
    const publish=await request.put(`/api/devices/${id}`,{headers,data:{...data,published:true,revision:1}});expect(publish.status()).toBe(200);
    await page.goto(`/e/${id}`);
    await expect(page.locator('.precautions strong')).toHaveText('先检查耗材');
    await expect(page.locator('.precautions ul>li')).toHaveCount(2);
    await expect(page.getByRole('link',{name:'官方说明',exact:true})).toHaveAttribute('href','https://bambulab.com');
    expect(await page.evaluate(()=>Boolean((window as unknown as {markdownInjected?:boolean}).markdownInjected))).toBe(false);
    await expect(page.locator('.markdown-body script,.markdown-body img,.markdown-body a[href^="javascript:"]')).toHaveCount(0);
    const visible=await guest.get(`/api/devices/${id}`);expect(visible.status()).toBe(200);const b=await visible.json();expect(b.device).not.toHaveProperty('price');expect(JSON.stringify(b)).not.toContain('内部');expect(b.attachments).toHaveLength(1);
    expect((await guest.get(`/api/files/${publicFileId}`)).status()).toBe(200);
    expect((await guest.get(`/api/files/${internalFileId}`)).status()).toBe(404);
    const account={email:`member-${stamp}@qa.local`,name:'验收成员',role:'member',password:'QA-Member-Password-2026!'};
    expect((await request.post('/api/users',{headers,data:account})).status()).toBe(201);
    memberId=(await (await request.get('/api/users')).json()).find((u:{email:string})=>u.email===account.email).id;
    await login(member,account.email,account.password);
    const memberData=await (await member.get(`/api/devices/${id}`)).json();expect(memberData.device.price).toBe(data.price);expect(memberData.attachments).toHaveLength(2);
    expect((await member.get(`/api/files/${internalFileId}`)).status()).toBe(200);expect((await member.get('/api/users')).status()).toBe(403);expect((await member.put(`/api/devices/${id}`,{headers,data:{...data,revision:2}})).status()).toBe(403);
    expect((await request.patch('/api/users',{headers,data:{id:memberId,role:'admin'}})).status()).toBe(200);
    expect((await (await member.get('/api/auth')).json()).user).toBeNull();
    await login(member,account.email,account.password);expect((await member.get('/api/users')).status()).toBe(200);
    expect((await member.post('/api/users',{headers,data:{email:`extra-${stamp}`,name:'新任管理员创建的成员',role:'member',password:'123456'}})).status()).toBe(201);
    expect((await member.patch('/api/users',{headers,data:{id:memberId,role:'member'}})).status()).toBe(400);
    expect((await request.patch('/api/users',{headers,data:{id:memberId,role:'member'}})).status()).toBe(200);
    expect((await (await member.get('/api/auth')).json()).user).toBeNull();await login(member,account.email,account.password);
    expect((await member.get('/api/users')).status()).toBe(403);
    expect((await request.get(`/api/labels?ids=${id}&format=svg`)).status()).toBe(409);
    const label=await request.get(`/api/labels?ids=${id}&format=svg&preview=1`);expect(label.status()).toBe(200);const labelBefore=await label.text();expect(labelBefore).toContain('90mm');
    const labelPdf=await request.get(`/api/labels?ids=${id}&format=pdf&preview=1`);expect(labelPdf.status()).toBe(200);expect((await labelPdf.body()).subarray(0,5).toString()).toBe('%PDF-');
    await page.goto(`/e/${id}`);await expect(page.getByRole('heading',{name:'验收设备',exact:true})).toBeVisible();await expect(page.getByText('不应泄露的内部备注')).toHaveCount(0);await expect(page.getByRole('link',{name:/说明书.pdf/})).toBeVisible();
    const html=await page.content();expect(html).not.toContain('76543.21');expect(html).not.toContain('内部供应商');
    const updated={...data,name:'修改后的验收设备',published:true,status:'停用',revision:2};expect((await request.put(`/api/devices/${id}`,{headers,data:updated})).status()).toBe(200);
    expect((await request.put(`/api/devices/${id}`,{headers,data:updated})).status()).toBe(409);
    const labelAfter=await (await request.get(`/api/labels?ids=${id}&format=svg&preview=1`)).text();expect(labelBefore.match(/<svg x="174"[\s\S]*?<\/svg>/)?.[0]).toBe(labelAfter.match(/<svg x="174"[\s\S]*?<\/svg>/)?.[0]);
    const stopped=await (await guest.get(`/api/devices/${id}`)).json();expect(stopped.device.status).toBe('停用');
    expect((await request.patch('/api/users',{headers,data:{id:memberId,active:false}})).status()).toBe(200);expect((await member.get('/api/auth')).status()).toBe(200);expect((await (await member.get('/api/auth')).json()).user).toBeNull();
  }finally{
    if(publicFileId)await request.delete(`/api/files/${publicFileId}`,{headers});if(internalFileId)await request.delete(`/api/files/${internalFileId}`,{headers});
    const current=await (await request.get(`/api/devices/${id}`)).json();await request.put(`/api/devices/${id}`,{headers,data:{...current.device,published:false,isDemo:true}});
    await guest.dispose();await member.dispose();
  }
});
test('Excel预览、重复编号回滚与模板导入',async({request})=>{
  await login(request);const template=await request.get('/api/import');expect(template.status()).toBe(200);
  const preview=await request.post('/api/import',{headers,multipart:{file:{name:'template.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:await template.body()}}});expect(preview.status()).toBe(200);const {rows}=await preview.json();expect(rows).toHaveLength(1);expect(rows[0].errors).toEqual([]);
  const data={...rows[0].data,code:`IMPORT-${stamp}`};
  const conflict=await request.post('/api/import',{headers,data:{rows:[data,data]}});expect(conflict.status()).toBe(409);
  let all=await (await request.get('/api/devices')).json();expect(all.some((d:{code:string})=>d.code===data.code)).toBe(false);
  const commit=await request.post('/api/import',{headers,data:{rows:[data]}});expect(commit.status()).toBe(200);
  all=await (await request.get('/api/devices')).json();const d=all.find((d:{code:string})=>d.code===data.code);expect(d.published).toBe(false);
  await request.put(`/api/devices/${d.id}`,{headers,data:{...d,isDemo:true}});
});
test('桌面、手机与标签页面无横向溢出，保存预览',async({page})=>{
  const exceptions:string[]=[];page.on('pageerror',e=>exceptions.push(e.message));
  await page.goto('/');await expect(page.getByRole('heading',{name:/设备目录/})).toBeVisible();await page.screenshot({path:'artifacts/catalog-desktop.png',fullPage:true});
  await page.getByLabel('搜索设备').fill('DEMO-001');await expect(page.getByRole('link',{name:/高速冷冻离心机/})).toBeVisible();await page.getByLabel('搜索设备').fill('找不到的设备');await expect(page.getByText('没有找到匹配的设备')).toBeVisible();
  await page.setViewportSize({width:390,height:844});await page.goto('/e/demo00000001');await expect(page.getByRole('heading',{name:'高速冷冻离心机'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'artifacts/equipment-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});await page.goto('/login');await page.getByLabel('邮箱').fill('admin@digitallab.local');await page.getByLabel('密码').fill('LocalLab-Review-2026!');await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page).toHaveURL('/');
  await page.goto('/admin/labels?device=demo00000001');await expect(page.getByAltText('90×60毫米设备信息标签预览')).toBeVisible();await page.screenshot({path:'artifacts/labels-desktop.png',fullPage:true});
  const svgDownload=page.waitForEvent('download');await page.getByRole('button',{name:'单张 SVG'}).click();await (await svgDownload).saveAs('artifacts/label-preview.svg');
  const pdfDownload=page.waitForEvent('download');await page.getByRole('button',{name:'90×60 PDF'}).click();await (await pdfDownload).saveAs('artifacts/label-preview.pdf');
  await page.getByRole('checkbox',{name:/紫外可见分光光度计/}).check();await page.getByRole('checkbox',{name:/超低温冰箱/}).check();
  const batchDownload=page.waitForEvent('download');await page.getByRole('button',{name:'A4 批量 PDF'}).click();await (await batchDownload).saveAs('artifacts/labels-a4-preview.pdf');
  await page.setViewportSize({width:390,height:844});await page.goto('/admin/devices/new');await expect(page.getByLabel('设备名称 *')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(exceptions).toEqual([]);
});
test('通过后台表单录入、补充SOP和上传说明书',async({page})=>{
  await page.goto('/login');await page.getByLabel('邮箱').fill('admin@digitallab.local');await page.getByLabel('密码').fill('LocalLab-Review-2026!');await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page).toHaveURL('/');
  await page.getByRole('link',{name:'录入设备'}).click();
  await expect(page).toHaveURL('/admin/devices/new');
  await page.waitForLoadState('networkidle');
  await expect(page.getByLabel('序列号')).toHaveCount(0);await expect(page.getByLabel('房间 / 位置')).toHaveCount(0);
  await page.getByLabel('设备分类').selectOption('3D打印与增材制造');
  await page.getByLabel('设备名称 *').fill('通过表单创建的验收设备');await page.getByLabel('设备编号 *').fill(`UI-${stamp}`);await page.getByRole('button',{name:'保存档案'}).click();await expect(page.getByText('档案已保存')).toBeVisible();await expect(page).toHaveURL(/\/admin\/devices\/[a-f0-9]{12}$/);
  await page.reload();await expect(page.getByLabel('设备分类')).toHaveValue('3D打印与增材制造');
  await page.getByRole('tab',{name:'购买与保修'}).click();
  await expect(page.getByLabel('购买日期',{exact:true})).toHaveAttribute('placeholder','yyyy/mm/dd');
  await page.getByLabel('购买日期',{exact:true}).fill('2026/10/06');
  await page.getByLabel('保修截止日期',{exact:true}).fill('2027/10/06');
  await page.getByLabel('购买渠道').selectOption('网店');
  await page.getByLabel('供应商 / 店铺名称',{exact:true}).fill('验收网店');
  await page.getByLabel('店铺 / 订单链接（可选）',{exact:true}).fill('https://shop.example.com/orders/123');
  await expect(page.getByLabel('销售 / 客服联系方式（可选）')).toHaveAttribute('type','text');
  await page.getByRole('button',{name:'保存档案'}).click();await expect(page.getByText('档案已保存')).toBeVisible();
  await page.reload();await page.getByRole('tab',{name:'购买与保修'}).click();
  await expect(page.getByLabel('购买日期',{exact:true})).toHaveValue('2026/10/06');
  await expect(page.getByLabel('购买渠道')).toHaveValue('网店');
  await expect(page.getByLabel('销售 / 客服联系方式（可选）')).toHaveValue('');
  await page.getByRole('tab',{name:'操作 SOP'}).click();await page.getByRole('button',{name:'添加操作步骤'}).click();await page.getByLabel('步骤名称').fill('核对实际操作要求');await page.getByLabel('操作内容').fill('此为自动化验收内容，不用于仪器操作。');await page.getByRole('button',{name:'保存档案'}).click();await expect(page.getByText('档案已保存')).toBeVisible();
  await page.getByRole('tab',{name:'照片与附件'}).click();await page.getByLabel('选择文件').setInputFiles({name:'验收说明书.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nfixture\n%%EOF')});await page.getByRole('button',{name:'上传附件',exact:true}).click();await expect(page.getByText('附件已上传')).toBeVisible();await expect(page.getByText('验收说明书.pdf',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'预览档案'}).click();await expect(page.getByRole('heading',{name:'通过表单创建的验收设备',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'核对实际操作要求'})).toBeVisible();
  const id=page.url().split('/').pop();const result=await page.request.get(`/api/devices/${id}`);const b=await result.json();for(const f of b.attachments)await page.request.delete(`/api/files/${f.id}`,{headers});
});
test('账号ID和六位密码可通过登录表单使用，重复ID不区分大小写',async({request,page})=>{
  await login(request);const email=`id-${stamp}`;
  expect((await request.post('/api/users',{headers,data:{email,name:'账号ID验收用户',role:'admin',password:'123456'}})).status()).toBe(201);
  expect((await request.post('/api/users',{headers,data:{email:email.toUpperCase(),name:'重复ID',role:'member',password:'123456'}})).status()).toBe(409);
  await page.goto('/login');await page.getByLabel('账号 ID / 邮箱').fill(email.toUpperCase());await page.getByLabel('密码').fill('123456');await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page).toHaveURL('/');
  await page.goto('/admin/users');await expect(page.getByRole('heading',{name:'成员管理'})).toBeVisible();await expect(page.getByRole('button',{name:'创建账号',exact:true})).toBeEnabled();await expect(page.getByLabel('角色：实验室管理员')).toBeEnabled();
});
