'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowUpRight, Plus, Search, SlidersHorizontal, Microscope, Box } from 'lucide-react';
import { Status,Empty } from './ui';
import {statuses,type Device} from '@/lib/types';
import PublishDrafts from './publish-drafts';
export default function Catalog({devices,admin}:{devices:Partial<Device>[];admin:boolean}){
  const [q,setQ]=useState(''),[category,setCategory]=useState(''),[status,setStatus]=useState('');
  const categories=[...new Set(devices.map(d=>d.category).filter(Boolean))];
  const filtered=devices.filter(d=>[d.name,d.code,d.model].join(' ').toLowerCase().includes(q.toLowerCase())&&(!category||d.category===category)&&(!status||d.status===status));
  return <><div className="page-heading"><div><div className="eyebrow">EQUIPMENT ARCHIVE / 设备档案</div><h1>设备目录<span className="count">{devices.length}</span></h1><p>从找到设备，到了解如何使用。</p></div>{admin&&<div className="button-group"><PublishDrafts devices={devices}/><Link href="/admin/devices/new" className="button primary"><Plus size={17}/>录入设备</Link></div>}</div><div className="summary-strip"><div><span>档案总数</span><strong>{devices.length}<small>台设备</small></strong></div><div><span>正常运行</span><strong>{devices.filter(d=>d.status==='正常').length}<i className="stat-dot good"/></strong></div><div><span>需关注</span><strong>{devices.filter(d=>['出借中','维护中','故障'].includes(d.status||'')).length}<i className="stat-dot warn"/></strong></div><div className="summary-note"><Box size={26}/><span>说明书、SOP与联系信息<br/>在每台设备的档案中集中查看</span></div></div><div className="directory-panel"><div className="filter-bar"><label className="search"><Search size={18}/><input aria-label="搜索设备" placeholder="搜索设备名称、编号或型号…" value={q} onChange={e=>setQ(e.target.value)}/>{q&&<button aria-label="清除搜索" onClick={()=>setQ('')}>×</button>}</label><div className="filters"><SlidersHorizontal size={16}/><select aria-label="设备分类" value={category} onChange={e=>setCategory(e.target.value)}><option value="">全部分类</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select aria-label="设备状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div></div><div className="list-caption">设备档案 <span>{filtered.length} 条结果</span></div>{filtered.length?<div className="equipment-list"><div className="equipment-row table-head"><span>设备名称 / 型号</span><span>设备编号</span><span>负责人 / 分类</span><span>当前状态</span><span/></div>{filtered.map(d=><Link key={d.id} href={`/e/${d.id}`} className="equipment-row"><div className="equipment-name"><span className="device-icon"><Microscope size={24}/></span><div><strong>{d.name}</strong><small>{d.model||'型号待补充'}{d.isDemo&&<em>示例</em>}{!d.published&&<em>草稿</em>}</small></div></div><span className="mono equipment-code">{d.code}</span><div className="equipment-location">{d.owner||'负责人待补充'}<small>{d.category||'分类待补充'}</small></div><Status value={d.status!}/><ArrowUpRight className="row-arrow" size={18}/></Link>)}</div>:<Empty>{devices.length?'没有找到匹配的设备，请调整搜索或筛选条件。':'暂无已发布设备档案。管理员可先录入设备。'}</Empty>}</div><div className="catalog-footnote"><span>扫码访问 · 手机友好</span><span>每台设备拥有独立、稳定的档案地址</span></div></>;
}
