'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect,useState } from 'react';
import { ArrowLeft,Save,Plus,Trash2,ExternalLink,Upload,LockKeyhole } from 'lucide-react';
import { emptyDevice,statuses,type Device,type DeviceData,type Attachment } from '@/lib/types';
import { api,Field,Notice,Empty } from './ui';
import { categoryOptions } from '@/lib/categories';
import DateField from './date-field';
import '@/app/dates.css';
import MarkdownContent from './markdown-content';
import SopEditor from './sop-editor';
const tabs=['基本信息','购买与保修','操作 SOP','维护记录','照片与附件','标签内容'];
export default function DeviceEditor({initial,files=[],categories=[]}:{initial?:Device;files?:Attachment[];categories?:string[]}){
  const [ready,setReady]=useState(false);
  useEffect(()=>setReady(true),[]);
  const [data,setData]=useState<DeviceData>(initial||emptyDevice),[id,setId]=useState(initial?.id),[revision,setRevision]=useState(initial?.revision),[tab,setTab]=useState(0),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[attachments,setAttachments]=useState(files),[file,setFile]=useState<File|null>(null),[kind,setKind]=useState('manual'),[visibility,setVisibility]=useState('public');const router=useRouter();
  function set<K extends keyof DeviceData>(key:K,value:DeviceData[K]){setData(d=>({...d,[key]:value}));setDirty(true);setSuccess('');}
  useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault();};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
  const input=(key:keyof DeviceData,label:string,type='text',required=false,hint?:string)=>type==='date'?<DateField key={key} label={label} value={String(data[key]??'')} onChange={v=>set(key,v as never)}/>:<Field key={key} label={label} hint={hint}><input disabled={!ready} type={type} value={String(data[key]??'')} required={required} onChange={e=>set(key,e.target.value as never)} /></Field>;
  async function refreshFiles(){const b=await api<{attachments:Attachment[]}>(`/api/devices/${id}`);setAttachments(b.attachments);}
  return <><Link href="/" className="back-link"><ArrowLeft size={16}/>设备目录</Link><div className="page-heading"><div><div className="eyebrow">ARCHIVE EDITOR</div><h1>{id?'编辑设备档案':'录入设备'}</h1><p>资料由管理员核对后发布。带 * 的字段为必填。</p></div>{id&&<Link className="button" href={`/e/${id}`}><ExternalLink size={16}/>预览档案</Link>}</div><form inert={!ready} onSubmit={async e=>{e.preventDefault();setError('');setSuccess('');setBusy(true);try{const result=await api<{id:string}>(id?`/api/devices/${id}`:'/api/devices',{method:id?'PUT':'POST',body:JSON.stringify({...data,revision})});const b=await api<{device:Device}>(`/api/devices/${result.id}`);setId(result.id);setRevision(b.device.revision);setData(b.device);setDirty(false);setSuccess('档案已保存');if(!id)router.replace(`/admin/devices/${result.id}`);router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><div className="editor-toolbar"><div className="tabs" role="tablist" aria-label="档案内容">{tabs.map((t,i)=><button type="button" role="tab" aria-selected={tab===i} key={t} onClick={()=>setTab(i)} className={i===tab?'selected':''}>{t}</button>)}</div></div><Notice message={error}/><Notice message={success} type="success"/><div className="panel editor-panel" role="tabpanel">
  {tab===0&&<><h2>基本信息</h2><div className="form-grid">{input('name','设备名称 *','text',true)}{input('code','设备编号 *','text',true,'唯一编号，如 LAB-001。二维码使用系统固定标识，不受编号修改影响。')}<Field label="设备分类"><select disabled={!ready} value={data.category} onChange={e=>set('category',e.target.value)}><option value="">请选择分类</option>{categoryOptions([...categories,data.category]).map(c=><option key={c} value={c}>{c}</option>)}</select></Field>{input('model','型号')}{input('manufacturer','厂家')}{input('owner','负责人')}{input('ownerPhone','负责人电话（公开）','tel')}{input('manufacturerPhone','厂家技术支持电话（公开）','tel')}<Field label="运行状态"><select value={data.status} onChange={e=>set('status',e.target.value as DeviceData['status'])}>{statuses.map(s=><option key={s}>{s}</option>)}</select></Field></div><Field label="主要参数"><textarea rows={4} value={data.parameters} onChange={e=>set('parameters',e.target.value)}/></Field></>}
  {tab===1&&<><h2><LockKeyhole size={18}/> 购买与保修</h2><p className="muted">此页内容仅登录成员可见；合同、发票在附件页上传。</p><div className="form-grid">{input('purchaseDate','购买日期','date')}{input('price','购买价格（元）','text',false,'非负金额，最多两位小数')}<Field label="购买渠道"><select value={data.purchaseChannel||''} onChange={e=>set('purchaseChannel',e.target.value)}><option value="">请选择渠道（可选）</option>{[...new Set(['网店','厂家直购','经销商','其他',data.purchaseChannel].filter(Boolean))].map(c=><option key={c}>{c}</option>)}</select></Field>{input('supplier','供应商 / 店铺名称')}{input('purchaseUrl','店铺 / 订单链接（可选）','url')}{input('salesPhone','销售 / 客服联系方式（可选）','text',false,'可填电话、客服账号或平台客服入口；无联系方式可留空')}{input('warrantyUntil','保修截止日期','date')}</div><Field label="内部备注"><textarea rows={4} value={data.internalNotes} onChange={e=>set('internalNotes',e.target.value)}/></Field></>}
  {tab===2&&<SopEditor data={data} onChange={patch=>{setData(d=>({...d,...patch}));setDirty(true);setSuccess('');}}/>}
  {tab===3&&<><h2>维护记录</h2><p className="muted">此页记录仅登录成员可见。</p>{data.maintenance.map((m,i)=><div className="repeat-item" key={m.id}><div className="repeat-heading">维护记录 {i+1}<button type="button" className="icon-button danger" aria-label={`删除维护记录${i+1}`} onClick={()=>set('maintenance',data.maintenance.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div><div className="form-grid"><Field label="日期"><input type="date" value={m.date} onChange={e=>set('maintenance',data.maintenance.map((v,j)=>j===i?{...v,date:e.target.value}:v))}/></Field><Field label="类型"><select value={m.kind} onChange={e=>set('maintenance',data.maintenance.map((v,j)=>j===i?{...v,kind:e.target.value}:v))}>{['故障','维修','保养','校准'].map(k=><option key={k}>{k}</option>)}</select></Field><Field label="下次计划日期"><input type="date" value={m.nextDate} onChange={e=>set('maintenance',data.maintenance.map((v,j)=>j===i?{...v,nextDate:e.target.value}:v))}/></Field></div><Field label="记录内容"><textarea rows={3} value={m.detail} onChange={e=>set('maintenance',data.maintenance.map((v,j)=>j===i?{...v,detail:e.target.value}:v))}/></Field></div>)}<button type="button" className="button" onClick={()=>set('maintenance',[...data.maintenance,{id:crypto.randomUUID(),date:'',kind:'保养',detail:'',nextDate:''}])}><Plus size={16}/>添加维护记录</button></>}
  {tab===4&&<><h2>照片与附件</h2>{!id?<Empty>请先保存设备档案，再上传文件。</Empty>:<><p className="muted">PDF / PNG / JPEG / WebP，单个文件最大20MB。合同和发票始终仅内部可见。附件上传后立即保存。</p><div className="form-grid"><Field label="附件类型"><select value={kind} onChange={e=>setKind(e.target.value)}>{[['manual','原装说明书'],['photo','设备照片'],['contract','购买合同'],['invoice','发票'],['other','其他附件']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></Field><Field label="可见范围"><select value={['contract','invoice'].includes(kind)?'internal':visibility} disabled={['contract','invoice'].includes(kind)} onChange={e=>setVisibility(e.target.value)}><option value="public">公开</option><option value="internal">仅登录成员</option></select></Field><Field label="选择文件"><input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></Field></div><button className="button" type="button" disabled={!file||busy} onClick={async()=>{setBusy(true);setError('');try{const f=new FormData();f.set('file',file!);f.set('deviceId',id);f.set('kind',kind);f.set('visibility',visibility);await api('/api/files',{method:'POST',body:f});await refreshFiles();setFile(null);setSuccess('附件已上传');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Upload size={16}/>{busy?'正在处理…':'上传附件'}</button><div className="file-list">{attachments.map(f=><div className="file-row" key={f.id}><a href={`/api/files/${f.id}`}><strong>{f.name}</strong><small>{f.visibility==='public'?'公开':'内部'} · {(f.size/1024/1024).toFixed(1)} MB</small></a><button type="button" className="icon-button danger" aria-label={`删除${f.name}`} onClick={async()=>{if(!confirm(`删除附件“${f.name}”？此操作无法撤销。`))return;try{await api(`/api/files/${f.id}`,{method:'DELETE'});await refreshFiles();}catch(e){setError((e as Error).message);}}}><Trash2 size={16}/></button></div>)}</div></>}</>}
  {tab===5&&<><h2>标签内容</h2><p className="muted">90×60mm标签只印稳定信息。型号、负责人和电话使用基本信息页的内容。</p>{input('labelName','标签简称','text',false,'最多36字；留空使用设备全名，超长时导出会提示修改。')}<Field label="重要提示 1（最多32字）"><input maxLength={32} value={data.labelTips[0]||''} onChange={e=>set('labelTips',[e.target.value,data.labelTips[1]||''].filter(Boolean))}/></Field><Field label="重要提示 2（最多32字）"><input maxLength={32} value={data.labelTips[1]||''} onChange={e=>set('labelTips',[data.labelTips[0]||'',e.target.value])}/></Field><p className="muted">提示必须经负责人确认。标签二维码不随设备资料修改而改变。</p>{id&&<Link className="button" href={`/admin/labels?device=${id}`}>打开标签预览</Link>}</>}
  </div><div className="save-bar"><div><label className="checkbox-label"><input type="checkbox" checked={data.published} onChange={e=>set('published',e.target.checked)}/>发布至公开目录</label><label className="checkbox-label"><input type="checkbox" checked={data.isDemo} onChange={e=>set('isDemo',e.target.checked)}/>标记为示例档案</label><small>{dirty?'有未保存的修改':'草稿仅管理员可见，已发布内容可供扫码查看。'}</small></div><button className="button primary" disabled={busy} type="submit"><Save size={17}/>{busy?'正在保存…':'保存档案'}</button></div></form></>;
}
