'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Download,Upload } from 'lucide-react';
import type { DeviceData } from '@/lib/types';
import { api,Field,Notice,Empty } from './ui';
type ImportRow={row:number;data:DeviceData|null;errors:string[]};
export default function ImportPanel(){const [rows,setRows]=useState<ImportRow[]>([]),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[file,setFile]=useState<File|null>(null);const router=useRouter();const valid=rows.length>0&&rows.every(r=>r.data&&!r.errors.length);return <><div className="page-heading"><div><div className="eyebrow">BATCH IMPORT</div><h1>批量导入设备</h1><p>先检查，再录入。导入设备统一保存为草稿。</p></div><a className="button" href="/api/import"><Download size={16}/>下载 Excel 模板</a></div><div className="panel"><h2>01 / 上传台账</h2><p className="muted">请使用.xlsx模板，删除示例行。每次最多200台、文件不超过2MB。SOP和附件在导入后补充。</p><Field label="设备台账文件"><input type="file" accept=".xlsx" onChange={e=>{setFile(e.target.files?.[0]||null);setRows([]);setError('');setSuccess('');}}/></Field><button disabled={!file||busy} className="button primary" onClick={async()=>{setBusy(true);setError('');try{const f=new FormData();f.set('file',file!);const result=await api<{rows:ImportRow[]}>('/api/import',{method:'POST',body:f});setRows(result.rows);if(!result.rows.length)setError('台账中没有设备数据');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Upload size={16}/>{busy?'正在检查…':'上传并预览'}</button></div><Notice message={error}/><Notice message={success} type="success"/><div className="panel"><div className="section-title"><h2>02 / 确认导入</h2><span className="section-extra">{rows.length} 条数据</span></div>{rows.length?<><div className="table-scroll"><table><thead><tr><th>行号</th><th>设备编号</th><th>设备名称</th><th>校验结果</th></tr></thead><tbody>{rows.map(r=><tr key={r.row}><td>{r.row}</td><td>{r.data?.code||'—'}</td><td>{r.data?.name||'—'}</td><td className={r.errors.length?'error-text':'success-text'}>{r.errors.length?r.errors.join('；'):'可导入'}</td></tr>)}</tbody></table></div>{!valid&&<p className="error-text">请修正全部错误后重新上传，系统不会跳过错误行。</p>}<button className="button primary" disabled={!valid||busy} onClick={async()=>{setBusy(true);setError('');try{const result=await api<{count:number}>('/api/import',{method:'POST',body:JSON.stringify({rows:rows.map(r=>r.data)})});setSuccess(`已导入${result.count}台设备，全部为草稿。请逐台核对后发布。`);setRows([]);setFile(null);router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>确认导入 {rows.length} 台设备</button></>:<Empty>上传台账后，这里会展示设备清单及校验结果。</Empty>}<Link className="back-link" href="/">返回设备目录</Link></div></>;}
