'use client';
import { useEffect,useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { Download,Printer,QrCode } from 'lucide-react';
import type { Device,Settings } from '@/lib/types';
import { Notice,Field,Empty } from './ui';
export default function LabelsPanel({devices,settings,previewUrl=''}:{devices:Device[];settings:Settings;previewUrl?:string}){
  const search=useSearchParams();const [selected,setSelected]=useState<string[]>(search.get('device')?[search.get('device')!]:devices[0]?[devices[0].id]:[]),[preview,setPreview]=useState(true),[image,setImage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const enabled=!!settings.baseUrl&&!!settings.scanVerifiedAt;
  // The optional LAN preview URL must never enable formal label export.
  if(previewUrl&&!settings.baseUrl) settings={...settings,baseUrl:previewUrl};
  useEffect(()=>{if(!selected[0]){setImage('');return;}const abort=new AbortController();let objectUrl='';setError('');setImage('');fetch(`/api/labels?ids=${selected[0]}&format=svg&preview=1`,{signal:abort.signal}).then(async r=>{if(!r.ok)throw new Error((await r.json()).error);objectUrl=URL.createObjectURL(await r.blob());setImage(objectUrl);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>{abort.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);};},[selected[0]]);
  async function download(format:'svg'|'pdf'|'a4'){setBusy(true);setError('');try{const ids=format==='svg'?selected.slice(0,1):selected;const r=await fetch(`/api/labels?ids=${ids.join(',')}&format=${format}&preview=${preview?'1':'0'}`);if(!r.ok)throw new Error((await r.json()).error);const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`${preview?'preview-':''}labels-${format}.${format==='svg'?'svg':'pdf'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <><div className="page-heading"><div><div className="eyebrow">EQUIPMENT LABELS</div><h1>信息标签</h1><p>贴在设备上的简明入口，与网页档案保持一致。</p></div><span className="size-badge">90 × 60 mm</span></div><Notice message={error}/>{!enabled&&<div className="notice warn">正式标签尚未启用。请在 <Link href="/admin/settings">实验室设置</Link> 中配置公网域名并完成手机扫码验证。</div>}<div className="labels-grid"><section className="panel"><div className="section-title"><h2>选择设备</h2><button className="text-button" onClick={()=>setSelected(selected.length===devices.length?[]:devices.map(d=>d.id))}>{selected.length===devices.length?'取消全选':'全选'}</button></div><div className="label-device-list">{devices.length?devices.map(d=><label key={d.id}><input type="checkbox" checked={selected.includes(d.id)} onChange={e=>setSelected(e.target.checked?[...selected,d.id]:selected.filter(id=>id!==d.id))}/><div><strong>{d.name}</strong><small>{d.code} · {d.isDemo?'示例':d.published?'已发布':'草稿'}</small></div><Link href={`/admin/devices/${d.id}`} className="text-button">编辑</Link></label>):<Empty>请先录入设备</Empty>}</div><div className="label-export"><Field label="导出模式"><select value={preview?'preview':'formal'} onChange={e=>setPreview(e.target.value==='preview')}><option value="preview">预览样张（请勿张贴）</option><option value="formal" disabled={!enabled}>正式标签（真实且已发布设备）</option></select></Field><div className="button-group"><button className="button" disabled={!selected.length||busy} onClick={()=>download('svg')}><Download size={16}/>单张 SVG</button><button className="button" disabled={!selected.length||busy} onClick={()=>download('pdf')}><Download size={16}/>90×60 PDF</button><button className="button primary" disabled={!selected.length||busy} onClick={()=>download('a4')}><Printer size={16}/>A4 批量 PDF</button></div><small>已选择 {selected.length} 台；单张SVG使用首台设备，PDF包含全部所选设备。</small></div></section><section className="label-preview-panel"><div className="preview-heading"><QrCode size={18}/>首台设备预览<span>含预览标记</span></div><div className="label-stage">{image?<img src={image} alt="90×60毫米设备信息标签预览"/>:<Empty>{selected.length?'正在生成标签或内容需要调整…':'选择设备以预览标签'}</Empty>}</div><div className="label-spec"><h2>打印与张贴</h2><p>PDF按实际尺寸输出。打印时选择 <strong>100% / 实际大小</strong>，关闭“适合页面”。A4每页排8张，包含6mm间距。</p><p>建议使用哑光覆膜不干胶。先打印一张，测量90×60mm尺寸并用手机扫码，再批量制作。</p><p>二维码约25mm，含完整白色静区。请勿裁切、覆盖或在二维码上叠加Logo。</p>{!settings.baseUrl&&<p className="error-text">尚未配置公网网址，样张二维码指向不可用的示例地址。</p>}</div></section></div></>;
}
