'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import type { Settings } from '@/lib/types';
import { api,Field,Notice } from './ui';
import QRCode from 'qrcode';
export default function SettingsForm({initial}:{initial:Settings}){
  const [s,setS]=useState(initial),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[qr,setQr]=useState('');const router=useRouter();
  return <><div className="page-heading"><div><div className="eyebrow">WORKSPACE SETTINGS</div><h1>实验室设置</h1><p>管理实验室身份与正式标签使用的公网网址。</p></div></div><form className="panel narrow-panel" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setSuccess('');try{const result=await api<Settings>('/api/settings',{method:'PUT',body:JSON.stringify(s)});setS(result);setQr('');setSuccess('设置已保存');router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Field label="实验室名称" hint="标签顶部使用此名称，建议24字以内。"><input required maxLength={32} value={s.labName} onChange={e=>setS({...s,labName:e.target.value})}/></Field><Field label="实验室公共联系方式"><input maxLength={200} value={s.contact} onChange={e=>setS({...s,contact:e.target.value})}/></Field><Field label="公网基础网址" hint="填写实际HTTPS域名，不带路径。修改域名会取消此前扫码验证；印刷标签后应长期保留该域名。"><input placeholder="https://lab.your-school.edu" value={s.baseUrl} onChange={e=>setS({...s,baseUrl:e.target.value})}/></Field><Field label="实验室标识图片" hint="PNG / JPEG / WebP。上传后需保存设置才能正式使用。">{s.logoId&&<div className="logo-preview"><img src={`/api/files/${s.logoId}`} alt="标识预览"/><button type="button" className="button" onClick={()=>setS({...s,logoId:''})}>移除标识</button></div>}<input type="file" accept=".png,.jpg,.jpeg,.webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const f=new FormData();f.set('file',file);f.set('kind','logo');f.set('visibility','public');const r=await api<{id:string}>('/api/files',{method:'POST',body:f});setS(v=>({...v,logoId:r.id}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}/></Field><Notice message={error}/><Notice message={success} type="success"/><button disabled={busy} className="button primary">{busy?'正在处理…':'保存设置'}</button></form><section className="panel narrow-panel"><h2>正式标签启用检查</h2><p className="muted">先保存公网网址，在手机上扫描下方验证二维码并登录管理员，确认页面成功打开。完成后刷新此页面。</p><Notice type={s.scanVerifiedAt?'success':'error'} message={s.scanVerifiedAt?`已验证：${new Date(s.scanVerifiedAt).toLocaleString('zh-CN')}；真实且已发布的设备可导出正式标签。`:'尚未验证：仅允许导出带“预览 · 请勿张贴”的样张。'}/><button className="button" disabled={!s.baseUrl||!s.scanToken||busy} onClick={async()=>{try{const saved=await api<Settings>('/api/settings');if(saved.baseUrl!==s.baseUrl)throw new Error('请先保存当前公网网址');setQr(await QRCode.toDataURL(`${saved.baseUrl}/verify/${saved.scanToken}`,{margin:4,width:240}));}catch(e){setError((e as Error).message);}}}>显示手机验证二维码</button>{qr&&<div className="verify-qr"><img src={qr} alt="公网手机扫码验证二维码"/><a href={`${s.baseUrl}/verify/${s.scanToken}`}>打开验证页面</a></div>}</section></>;
}
